<?php

use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;
use PHPUnit\Framework\TestCase;
use ExampleHttpClient\ExampleClient;
use ExampleHttpClient\ExampleException;

class ExampleClientTest extends TestCase
{

    private ExampleClient $client;
    private MockHandler $mock;
    private ExampleComment $comment;
    private ExampleComment $commentWithoutId;

    protected function setUp(): void
    {
        $this->mock = new MockHandler();
        $handlerStack = HandlerStack::create($this->mock);
        $this->client = new ExampleClient(['handler' => $handlerStack]);
        $this->comment = new ExampleComment(['id' => 1, 'name' => 'Roman', 'text' => 'First comment']);
        $this->commentWithoutId = new ExampleComment(['name' => 'Roman', 'text' => 'Second comment']);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetComments() {
        $this->mock->append(new Response(200,
            ['Content-Type' => 'application/json; charset=utf-8'],
            json_encode([['id' => 1, 'name' => 'Roman', 'text' => 'First comment']])
        ));
        $comments = $this->client->getComments();
        $this->assertEquals(1, $comments[0]->id);
        $this->assertEquals('Roman', $comments[0]->name);
        $this->assertEquals('First comment', $comments[0]->text);
    }

    public function testGetCommentsFail() {
        $this->expectException(ExampleException::class);
        $this->expectExceptionMessage('Problem with the http request, please try again later');
        $this->mock->append(new Response(500));
        $this->client->getComments();
    }

    public function testGetCommentsInvalidData() {
        $this->expectException(ExampleException::class);
        $this->expectExceptionMessage('The service returned invalid data');
        $this->mock->append(new Response(200,
            ['Content-Type' => 'application/text; charset=utf-8'],
            'data'
        ));
        $this->client->getComments();
    }

    public function testGetCommentsInvalidJsonData() {
        $this->expectException(ExampleException::class);
        $this->expectExceptionMessage('Class \'ExampleHttpClient\ExampleComment\' does not contain the \'uid\' attribute');
        $this->mock->append(new Response(200,
            ['Content-Type' => 'application/json; charset=utf-8'],
            json_encode([['uid' => 1, 'surname' => 'Kadykov', 'car' => 'Toyota']])
        ));
        $this->client->getComments();
    }

    public function testAddComment() {
        $this->mock->append(new Response(200,
            ['Content-Type' => 'application/json; charset=utf-8'],
            json_encode([['id' => 1, 'name' => 'Roman', 'text' => 'First comment']])
        ));
        $comments = $this->client->addComment($this->commentWithoutId);
        $this->assertEquals(1, $comments[0]->id);
        $this->assertEquals('Roman', $comments[0]->name);
        $this->assertEquals('First comment', $comments[0]->text);
    }

    public function testAddCommentFail() {
        $this->expectException(ExampleException::class);
        $this->expectExceptionMessage('Problem with the http request, please try again later');
        $this->mock->append(new Response(500));
        $this->client->addComment();
    }

    public function testAddCommentInvalidData() {
        $this->expectException(ExampleException::class);
        $this->expectExceptionMessage('The service returned invalid data');
        $this->mock->append(new Response(200,
            ['Content-Type' => 'application/text; charset=utf-8'],
            'data'
        ));
        $this->client->addComment();
    }

    public function testAddCommentInvalidJsonData() {
        $this->expectException(ExampleException::class);
        $this->expectExceptionMessage('Class \'ExampleHttpClient\ExampleComment\' does not contain the \'uid\' attribute');
        $this->mock->append(new Response(200,
            ['Content-Type' => 'application/json; charset=utf-8'],
            json_encode([['uid' => 1, 'surname' => 'Kadykov', 'car' => 'Toyota']])
        ));
        $this->client->addComment();
    }
}
